[package]
name = "rustycar"
version = "0.1.0"
authors = ["dawid.nowak <nowakd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bytes = "0.4.4"
futures-core-preview = "=0.3.0-alpha.19"
futures-channel-preview = "=0.3.0-alpha.19"
futures-util-preview = "=0.3.0-alpha.19"
futures-executor-preview = "=0.3.0-alpha.19"
futures = "=0.3.0"
#futures-core= "=0.3.0"
#futures-channel = "=0.3.0"
#futures-util = "=0.3.0"
#futures-executor = "=0.3.0"

http = "0.1.15"
http-body = "=0.2.0-alpha.3"
httparse = "1.0"
h2 = "=0.2.0-alpha.3"
iovec = "0.1"
itoa = "0.4.1"
log = "0.4"
pin-project = "0.4"
time = "0.1"
tower-service = "=0.3.0-alpha.2"
tower-make = { version = "=0.3.0-alpha.2a", features = ['io'] }
tokio-executor = "=0.2.0-alpha.6"
tokio-io = "=0.2.0-alpha.6"
tokio-sync = "=0.2.0-alpha.6"
want = "0.3"


# Optional

net2 = { version = "0.2.32", optional = true }
tokio = { version = "=0.2.0-alpha.6", optional = false, default-features = false, features = ["rt-full"] }
tokio-net = { version = "=0.2.0-alpha.6", optional = false, features = ["tcp"] }
tokio-timer = { version = "=0.3.0-alpha.6", optional = true }
tokio-rustls = "0.12.0-alpha.8"
#tokio-tcp = { version = "=0.2.0-alpha.1", optional = false}


rustls = "0.16"
async-stream = "0.1.2"


#hyper = { path = "../hyper" , features = ["runtime","unstable-stream"]}
hyper = {version = "0.13.0-alpha.4", features = ["runtime","unstable-stream"]}

clap = {version = ">=2.33.0", features = ["yaml"]}
crossbeam-channel = "0.4.0"

env_logger = "*"
serde = {version = "*", features = ["derive"] }
serde_json = {version = "= 1.0.41"}

rdkafka  = { version = "~0.21"}
rdkafka-sys = { version ="1.0.0"}
sled = "*"
