[package]
name = "rustycar"
version = "0.1.0"
authors = ["dawid.nowak <nowakd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
futures = "0.1"
http = "0.1"
hyper = "0.12"
rustls = "0.13"
tokio-io = "0.1.1"
tokio-rustls = "0.7"
tokio-tcp = "0.1"
webpki = "0.18.1"
webpki-roots = "0.15"
tokio = "0.1"
kafka = "*"
log = "0.4"
pretty_env_logger = "*"
clap = {version = ">=2.33.0", features = ["yaml"]}
serde = {version = "*", features = ["derive"] }
serde_json = {version = "= 1.0.41"}
crossbeam-channel = "*"
sled = "*"
sha2 = "*"
bincode ="*"
hex-literal="*"
rdkafka  = { version = "~0.20"}
rdkafka-sys = { version ="^0.11.6-1"}
natsclient = "*"


[features]
with_nats = []



#
#hyper = "=0.12.35"
#
#bytes = "0.4.6"
#futures = "0.1.21"
#futures-cpupool = { version = "0.1.6", optional = true }
#http = "0.1.15"
#http-body = "0.1"
#httparse = "1.0"
#h2 = "0.1.13"
#iovec = "0.1"
#itoa = "0.4.1"
#
#
#net2 = { version = "0.2.32", optional = true }
#time = "0.1"
#tokio = { version = "0.1.14", optional = true, default-features = false, features = ["rt-full"] }
#tokio-buf = "0.1"
#tokio-executor = { version = "0.1.0", optional = true }
#tokio-io = "0.1"
#tokio-reactor = { version = "0.1", optional = true }
#tokio-tcp = { version = "0.1", optional = true }
#tokio-threadpool = { version = "0.1.16", optional = true }
#tokio-timer = { version = "0.2", optional = true }
#want = "0.2"
