[package]
name = "rustycar"
version = "0.1.0"
authors = ["Dawid Nowak <nowakd@gmail.com>"]
repository = "https://github.com/swir-rs/swir"
readme = "README.md"
license = "Apache-2.0"
description = "Sidecar Written in Rust"
keywords = ["sidecar", "rest", "messaging","cloudcomputing"]
categories = ["sidecar"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.4"
futures = "=0.3"
futures-core= "=0.3"
futures-channel = "=0.3"
futures-util = "=0.3"
futures-executor = "=0.3"

http = "0.2"
http-body = "=0.3"
httparse = "1.0"
h2 = "=0.2"
iovec = "0.1"
itoa = "0.4.1"
log = "0.4"
pin-project = "0.4"
time = "0.1"
tower-service = "=0.3"
tower-make = { version = "=0.3.0"}
want = "0.3"

# Optional
net2 = { version = "0.2.32", optional = true }
tokio = { version = "=0.2.2", features = ["full"]}
tokio-rustls = "0.12.0-alpha.8"
rustls = "0.16"
async-stream = "0.2"
hyper = "0.13.0"
#hyper = { path = "../hyper" , features = ["runtime","stream"]}
clap = {version = ">=2.33.0", features = ["yaml"]}
env_logger = "*"
serde = {version = "*", features = ["derive"] }
serde_json = {version = "= 1.0.41"}
rdkafka = { version="0.22", path = "../rust-rdkafka" }
rdkafka-sys = { version = "1.2.1", default-features = false,path = "../rust-rdkafka/rdkafka-sys"}
sled = "*"
nats = {version="*",optional=true}

prost = "0.5"
prost-derive = "0.5"
tonic = {version="0.1.0-alpha.6", path ="../tonic/tonic", optional=false}


[build-dependencies]
tonic-build = { version="0.1.0-alpha.6", path ="../tonic/tonic-build" }

[features]
with_nats = ["nats"]

#with_grpc = ["tonic"]