[package]
name = "rustycar"
version = "0.1.0"
authors = ["dawid.nowak <nowakd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bytes = "0.5"
futures = "=0.3"
futures-core= "=0.3"
futures-channel = "=0.3"
futures-util = "=0.3"
futures-executor = "=0.3"

http = "0.2"
http-body = "=0.3"
httparse = "1.0"
h2 = "=0.2"
iovec = "0.1"
itoa = "0.4.1"
log = "0.4"
pin-project = "0.4"
time = "0.1"
tower-service = "=0.3"
tower-make = { version = "=0.3.0"}
want = "0.3"

# Optional
net2 = { version = "0.2.32", optional = true }
tokio = { version = "=0.2.2", features = ["full"]}
tokio-rustls = "0.12.0-alpha.8"
#tokio-tcp = { version = "=0.2.0-alpha.1", optional = false}
rustls = "0.16"
async-stream = "0.2"
hyper = { path = "../hyper" , features = ["runtime","stream"]}
#hyper = {version = "0.13.0-alpha.4", features = ["runtime","stream"]}
clap = {version = ">=2.33.0", features = ["yaml"]}
env_logger = "*"
serde = {version = "*", features = ["derive"] }
serde_json = {version = "= 1.0.41"}
rdkafka = { path = "../rust-rdkafka" }
rdkafka-sys = { path = "../rust-rdkafka/rdkafka-sys", version = "1.2.1", default-features = false }
#rdkafka  = { version = "~0.21"}
#rdkafka-sys = { version ="1.0.0"}
sled = "*"
