version: '2'
services:
  swir:
    networks:
      - swir-net
    image: swir:with_kafka
    ports:
      - "8080:8080"
      - "8443:8443"
  swir-kafka-sink:
    networks:
      - swir-net
    image: swir-kafka-sink
    depends_on:
      - "swir"
  swir-java-client:
    networks:
      - swir-net
    image: swir-java-client
    depends_on:
      - "swir"
# Optional. Enable only to do some benchmarks without SWIR
#  kafka-java-client:
#    networks:
#      - swir-net
#    image: kafka-java-client
#    depends_on:
#      - "swir"
networks:
  swir-net:
    external:
      name: docker_swir-net